# Docker compose for postgres and pgadmin

version: "3.5"

services:
    client:
        container_name: ft_transcendance_client
        build:
            context: .
            args:
                NODE_ENV: ${NODE_ENV:-production}
        networks:
            - ft_transcendance
        ports:
            - 127.0.0.1:4000:4000
        env_file:
            - ".env"
        environment:
            TZ: Europe/Paris
        volumes:
            # Mount code to avoid rebuild container to refresh code
            - ./components:/app/components
            - ./config:/app/config
            - ./entrypoint.sh:/app/entrypoint.sh
            - ./jsconfig.json:/app/jsconfig.json
            - ./logs:/app/logs
            - ./nuxt.config.js:/app/nuxt.config.js
            - ./package.json:/app/package.json
            - ./pages:/app/pages
            - ./static:/app/static
            - ./store:/app/store
            - ./stylelint.config.js:/app/stylelint.config.js
            - ./tailwind.config.js:/app/tailwind.config.js
            - ./tsconfig.json:/app/tsconfig.json
            - ./layouts:/app/layouts
            - ./assets:/app/assets
        healthcheck:
            disable: false
        restart: unless-stopped

networks:
    ft_transcendance:
        external: false
