# Commands to start on workspace startup
tasks:
  - init: stat dev
    command: bash start_dev.sh
# Ports to expose on workspace startup
ports:
  - port: 80
    onOpen: open-browser
    visibility: public