ft_proxy:
  image: nginx
  volumes:
   - ./templates:/etc/nginx/templates
   - ./ssl:/etc/letsencrypt
  ports:
   - "8080:80"
   - "8443:443"
  environment:
   - NGINX_HOST=transcendance.nollium.com
   - NGINX_HTTP_PORT=80
   - NGINX_HTTPS_PORT=443
   - NGINX_DEV_HOST=localhost
   - API_HOST=${API_HOST}
   - API_PORT=${API_PORT}
   - CLIENT_HOST=${CLIENT_HOST}
   - CLIENT_PORT=${CLIENT_PORT}
   - SSL_CERTIFICATE=/etc/letsencrypt/live/transcendance.nollium.com/fullchain.pem
   - SSL_KEY=/etc/letsencrypt/live/transcendance.nollium.com/privkey.pem
   - SSL_NGINX_OPTIONS=/etc/letsencrypt/options-ssl-nginx.conf
   - SSL_NGINX_DHPARAM=/etc/letsencrypt/ssl-dhparams.pem

