version: "3.5"

services:
    api:
        #    container_name: ft_api
        build:
            context: .
            args:
                NODE_ENV: ${NODE_ENV:-production}
                API_PORT: ${API_PORT:-3000}
        networks:
            - default
            - ft_transcendance
        ports:
            - 0.0.0.0:3000:${API_PORT:-3000}
        env_file:
            - ".env"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ft_db
        volumes:
            # Mount code to avoid rebuild container to refresh code
            - ./src:/app/src
            - ./tsconfig.json:/app/tsconfig.json
            - ./tsconfig.build.json:/app/tsconfig.build.json
            - ./config.json:/app/config.json
        healthcheck:
            disable: false
        restart: unless-stopped

    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ft_db
        ports:
            - "5432:5432"

networks:
    ft_transcendance:
        external: false
