version: '3.5'

services:
  api:
    container_name: ft_api
    build: .
    networks:
    - default
    - ft_transcendance
    ports:
    - 0.0.0.0:3000:3000
    environment:
# Values from parent shell, overriden by values from .env
    - INTRA42_UID=${INTRA42_UID}
    - INTRA42_SECRET=${INTRA42_SECRET}
# Config file containing credentials values
    - CONFIG_FILE=/opt/.env
    volumes:
# Add env config file
    - ./.env:/opt/.env
# Mount code to avoid rebuild container to refresh code
    - ./src:/app/src
    - ./entrypoint.sh:/app/entrypoint.sh
    healthcheck:
      disable: false
    restart: unless-stopped

networks:
  ft_transcendance:
    external: false
